CREATE DATABASE CNPMNC
USE CNPMNC
GO
 CREATE TABLE NHACUNGCAP
 (
	NCCID INT IDENTITY(1,1) PRIMARY KEY,
	TENNCC NVARCHAR(100),
	SDT CHAR(13),
	DIACHI NVARCHAR(250)
 )
  CREATE TABLE PHIEUNHAP
  (
	PHIEUNHAPID INT IDENTITY(1,1) PRIMARY KEY,
	NGAYNHAP DATETIME DEFAULT(GETDATE()),
	NCCID INT,
	FOREIGN KEY(NCCID) REFERENCES NHACUNGCAP(NCCID)

  )
  
  CREATE TABLE CTPHIEUNHAP
  (
	CTPHIEUNHAPID INT IDENTITY(1,1) PRIMARY KEY,
	DIENTHOAIID INT,
	PHIEUNHAPID INT,
	TENDT NVARCHAR(250),
	SOLUONGNHAP INT,
	GIANHAP DECIMAL,
	FOREIGN KEY(DIENTHOAIID) REFERENCES DIENTHOAI(DIENTHOAIID),
	FOREIGN KEY(PHIEUNHAPID) REFERENCES PHIEUNHAP(PHIEUNHAPID)
  )
  CREATE TABLE HANG
  (
	HANGID INT IDENTITY(1,1) PRIMARY KEY,
	TENHANG NVARCHAR(250),
	HINH NVARCHAR(250)
  )
 

 CREATE TABLE DIENTHOAI
  (
	DIENTHOAIID INT IDENTITY(1,1) PRIMARY KEY,
	TENDT NVARCHAR(250),
	SOLUONGTON INT,
	HINHANH1 NVARCHAR(MAX),
	HINHANH2 NVARCHAR(MAX),
	HINHANH3 NVARCHAR(MAX),
	GIABAN int,
	GIAGIAM int,
	HANGID INT,
	NCCID INT,
	MAUSAC NVARCHAR(250),
	PHANTRAMGIAM int,
	FOREIGN KEY(HANGID) REFERENCES HANG(HANGID),
	FOREIGN KEY(NCCID) REFERENCES NHACUNGCAP(NCCID),
	
  )
 
  CREATE TABLE THONGSOKT
  (
	THONGSOKTID INT IDENTITY(1,1) PRIMARY KEY,
	DIENTHOAIID INT,
	MANHINH NVARCHAR(250),
	DOPHANGIAI NVARCHAR(250),
	CAMERA NVARCHAR(250),
	HEDH NVARCHAR(250),
	CHIPXULY NVARCHAR(250),
	ROM NVARCHAR(10),
	RAM NVARCHAR(10),
	MANGDIDONG NVARCHAR(250),
	SOKESIM NVARCHAR(250),
	PIN NVARCHAR(250),
	FOREIGN KEY(DIENTHOAIID) REFERENCES DIENTHOAI(DIENTHOAIID)
  )
 
  
  CREATE TABLE DANHGIASANPHAM
  (
	DANHGIAID INT IDENTITY(1,1) PRIMARY KEY,
	KHACHHANGID INT,
	DIENTHOAIID INT,
	DANHGIA NVARCHAR(500),
	NGAYTAO DATETIME DEFAULT(GETDATE()),
	FOREIGN KEY(DIENTHOAIID) REFERENCES DIENTHOAI(DIENTHOAIID),
	FOREIGN KEY(KHACHHANGID) REFERENCES KHACHHANG(KHACHHANGID)
  )
  
  CREATE TABLE DONHANG
  (
	DONHANGID INT IDENTITY(1,1) PRIMARY KEY,
	KHACHHANGID INT,
	TRANGTHAIID INT,
	NGAYTAO DATETIME DEFAULT(GETDATE()),
	GIAMGIA NVARCHAR(250),
	THANHTIEN DECIMAL,
	FOREIGN KEY(KHACHHANGID) REFERENCES KHACHHANG(KHACHHANGID),
	FOREIGN KEY(TRANGTHAIID) REFERENCES TRANGTHAIDH(TRANGTHAIID)
  )

  Alter table DONHANG
  ADD TENKH NVARCHAR(100)
  Alter table DONHANG
  ADD DIACHI NVARCHAR(100)
  Alter table DONHANG
  ADD SDT CHAR(12)

  
   CREATE TABLE CTDONHANG
   (
	CTDONHANGID INT IDENTITY(1,1) PRIMARY KEY,
	DIENTHOAIID INT,
	DONHANGID INT,
	SOLUONGMUA INT,
	TONGTIEN DECIMAL,
	FOREIGN KEY(DIENTHOAIID) REFERENCES DIENTHOAI(DIENTHOAIID),
	FOREIGN KEY(DONHANGID) REFERENCES DONHANG(DONHANGID)
   )

   CREATE TABLE KHACHHANG
   (
	KHACHHANGID INT IDENTITY(1,1) PRIMARY KEY,
	HOTEN NVARCHAR(250),
	EMAIL NVARCHAR(250),
	MATKHAU NVARCHAR(250),
	NHAPLAIMK NVARCHAR(250),
	SDT CHAR(13),
	DIACHI NVARCHAR(250),
	LOAIKHID INT,
	FOREIGN KEY(LOAIKHID) REFERENCES LOAIKH(LOAIKHID),
   )
   CREATE TABLE LOAIKH
   (
	LOAIKHID INT IDENTITY(1,1) PRIMARY KEY,
	TENLOAI NVARCHAR(250),
	CHIETKHAU DECIMAL
   )

   CREATE TABLE PHANHOI
   (
	PHANHOIID INT IDENTITY(1,1) PRIMARY KEY,
	KHACHHANGID INT,
	PHANHOI NVARCHAR(MAX)
   )
   CREATE TABLE ADMIN
   (
	ADMINID INT IDENTITY(1,1) PRIMARY KEY,
	EMAIL NVARCHAR(250),
	TENAD NVARCHAR(250),
	MATKHAU NVARCHAR(250)
   )
   CREATE TABLE PTTHANHTOAN
   (
	PTTHANHTOANID INT IDENTITY(1,1) PRIMARY KEY,
	TENPT NVARCHAR(250)
   )
   CREATE TABLE TRANGTHAIDH
   (
	TRANGTHAIID INT IDENTITY(1,1) PRIMARY KEY,
	TENTT NVARCHAR(250)
   )

   