//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEUNHAP
    {
        public int CTPHIEUNHAPID { get; set; }
        public Nullable<int> DIENTHOAIID { get; set; }
        public Nullable<int> PHIEUNHAPID { get; set; }
        public string TENDT { get; set; }
        public Nullable<int> SOLUONGNHAP { get; set; }
        public Nullable<decimal> GIANHAP { get; set; }
    
        public virtual DIENTHOAI DIENTHOAI { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
    }
}
