//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DANHGIASANPHAM
    {
        public int DANHGIAID { get; set; }
        [Display(Name = "Tên khách hàng")]
        public Nullable<int> KHACHHANGID { get; set; }
        [Display(Name = "Điện thoại")]
        public Nullable<int> DIENTHOAIID { get; set; }
        [Display(Name = " Đánh giá")]
        public string DANHGIA { get; set; }
        [Display(Name = "Ngày đánh giá")]
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    
        public virtual DIENTHOAI DIENTHOAI { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
