//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class DIENTHOAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIENTHOAI()
        {
            HINHANH1 = "~/Areas/Admin/Content/img/iconanh.png";
            HINHANH2 = "~/Areas/Admin/Content/img/iconanh.png";
            HINHANH3 = "~/Areas/Admin/Content/img/iconanh.png";
            this.CTPHIEUNHAPs = new HashSet<CTPHIEUNHAP>();
            this.CTDONHANGs = new HashSet<CTDONHANG>();
            this.CTPHIEUNHAPs = new HashSet<CTPHIEUNHAP>();
            this.DANHGIASANPHAMs = new HashSet<DANHGIASANPHAM>();
            this.THONGSOKTs = new HashSet<THONGSOKT>();
        }

        [NotMapped]
        public List<DIENTHOAI> ListCateDT { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage1 { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage2 { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage3 { get; set; }
        public int DIENTHOAIID { get; set; }
        [Display(Name = "Tên điện thoại")]
        public string TENDT { get; set; }
        [Display(Name = "Số lượng tồn")]
        public Nullable<int> SOLUONGTON { get; set; }
        [Display(Name = "Ảnh 1")]
        public string HINHANH1 { get; set; }
        [Display(Name = "Ảnh 2")]
        public string HINHANH2 { get; set; }
        [Display(Name = "Ảnh 3")]
        public string HINHANH3 { get; set; }
        [Display(Name = "Giá bán")]
        [DisplayFormat(DataFormatString = "{0:0,0 đ}", ApplyFormatInEditMode = false)]
        public Nullable<int> GIABAN { get; set; }
        [Display(Name = "Giá giảm")]
        [DisplayFormat(DataFormatString = "{0:0,0 đ}", ApplyFormatInEditMode = false)]
        public Nullable<int> GIAGIAM { get; set; }
        [Display(Name = "Tên hãng")]
        public Nullable<int> HANGID { get; set; }
        [Display(Name = "Tên nhà cung cấp")]
        public Nullable<int> NCCID { get; set; }
        [Display(Name = "Màu sắc")]
        public string MAUSAC { get; set; }
        [Display(Name = "Phần trăm giảm")]
        public Nullable<int> PHANTRAMGIAM { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDONHANG> CTDONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAP> CTPHIEUNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIASANPHAM> DANHGIASANPHAMs { get; set; }
        public virtual HANG HANG { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGSOKT> THONGSOKTs { get; set; }
    }
}