//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CTDONHANGs = new HashSet<CTDONHANG>();
        }

        public int DONHANGID { get; set; }
        [Display(Name = "Người đặt")]
        public Nullable<int> KHACHHANGID { get; set; }
        [Display(Name = "Trạng thái đơn hàng")]
        public Nullable<int> TRANGTHAIID { get; set; } = 1;
        [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        [Display(Name = "Giá giảm")]
        public string GIAMGIA { get; set; }
        [DisplayFormat(DataFormatString = "{0:0,0 đ}", ApplyFormatInEditMode = false)]
        [Display(Name = "Thành tiền")]
        public Nullable<decimal> THANHTIEN { get; set; }
        [Display(Name = "Tên người nhận")]
        public string TENKH { get; set; }
        [Display(Name = "Địa chỉ")]
        public string DIACHI { get; set; }
        [Display(Name = "Số điện thoại")]
        public string SDT { get; set; }
        [Display(Name = "Phương thức thanh toán")]
        public Nullable<int> PTTHANHTOANID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDONHANG> CTDONHANGs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual TRANGTHAIDH TRANGTHAIDH { get; set; }
        public virtual PTTHANHTOAN PTTHANHTOAN { get; set; }
    }
}