//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANG()
        {
            HINH = "~/Areas/Admin/Content/img/iconanh.png";
            this.DIENTHOAIs = new HashSet<DIENTHOAI>();
        }
        [NotMapped]
        public HttpPostedFileBase UploadImage1 { get; set; }
        [NotMapped]
        public List<HANG> ListCate { get; set; }

        public int HANGID { get; set; }
        [Display(Name = "Tên Hãng")]
        public string TENHANG { get; set; }
        [Display(Name = "Ảnh")]
        public string HINH { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIENTHOAI> DIENTHOAIs { get; set; }
    }
}