//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            HINH = "~/Areas/Admin/Content/img/iconanh.png";
            this.DANHGIASANPHAMs = new HashSet<DANHGIASANPHAM>();
            this.DONHANGs = new HashSet<DONHANG>();
            this.PHANHOIs = new HashSet<PHANHOI>();
        }
        [NotMapped]
        public HttpPostedFileBase UploadImage1 { get; set; }
        public int KHACHHANGID { get; set; }
        [Display(Name = "Họ tên")]
        public string HOTEN { get; set; }
        [Display(Name = "Email")]
        public string EMAIL { get; set; }
        [Display(Name = "Mật khẩu")]
        public string MATKHAU { get; set; }
        [Display(Name = "Nhập lại mật khẩu")]

        public string NHAPLAIMK { get; set; }
        [Display(Name = "Số điện thoại")]
        public string SDT { get; set; }
        [Display(Name = "Địa chỉ")]
        public string DIACHI { get; set; }
        [Display(Name = "Loại khách hàng")]
        public Nullable<int> LOAIKHID { get; set; }
        [Display(Name = "Hình")]
        public string HINH { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIASANPHAM> DANHGIASANPHAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        public virtual LOAIKH LOAIKH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANHOI> PHANHOIs { get; set; }
    }
}