//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PHANHOI
    {
        public int PHANHOIID { get; set; }
        [Display(Name = "Tên khách hàng")]
        public Nullable<int> KHACHHANGID { get; set; }
        [Display(Name = "Thông tin phản hồi")]
        public string PHANHOI1 { get; set; }
        [Display(Name = "Email")]
        public string EMAIL { get; set; }
        [Display(Name = "Số điện thoại")]
        public string SDT { get; set; }

        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}