//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANHOI
    {
        public int PHANHOIID { get; set; }
        public Nullable<int> KHACHHANGID { get; set; }
        public string PHANHOI1 { get; set; }
    }
}
